# Generated by Django 5.0.14 on 2026-02-11 20:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for QR (e.g., LOCAL_01)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name (e.g., Meriendahaus Principal)', max_length=100)),
                ('allowed_ips', models.JSONField(default=list, help_text='List of allowed public IPs or CIDRs, e.g., ["85.123.45.67", "192.168.1.0/24"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique code for QR (e.g., LOCAL_01)', max_length=20)),
                ('name', models.CharField(help_text='Display name (e.g., Meriendahaus Principal)', max_length=100)),
                ('allowed_ips', models.JSONField(default=list, help_text='List of allowed public IPs or CIDRs, e.g., ["85.123.45.67", "192.168.1.0/24"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Local',
                'verbose_name_plural': 'historical Locales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTimeEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='Entrada')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Salida')),
                ('check_in_ip', models.GenericIPAddressField(verbose_name='IP entrada')),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP salida')),
                ('is_manual', models.BooleanField(default=False, help_text='True if created/modified by admin', verbose_name='Entrada manual')),
                ('notes', models.TextField(blank=True, help_text='Required when is_manual=True (reason for manual entry)', verbose_name='Notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clock.location', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'historical Fichaje',
                'verbose_name_plural': 'historical Fichajes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='Entrada')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Salida')),
                ('check_in_ip', models.GenericIPAddressField(verbose_name='IP entrada')),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP salida')),
                ('is_manual', models.BooleanField(default=False, help_text='True if created/modified by admin', verbose_name='Entrada manual')),
                ('notes', models.TextField(blank=True, help_text='Required when is_manual=True (reason for manual entry)', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='clock.location', verbose_name='Local')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_entries', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Fichaje',
                'verbose_name_plural': 'Fichajes',
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['user', 'check_in'], name='clock_timee_user_id_4d7840_idx'), models.Index(fields=['user', '-check_in'], name='clock_timee_user_id_4df580_idx')],
            },
        ),
    ]
